development:
  adapter: postgresql
  encoding: unicode
  database: worksense
  pool: 5
  timeout: 5000
 
test:
  adapter: postgresql
  encoding: unicode
  database: worksense
  pool: 5
  timeout: 5000

production:
<<: *default
  adapter: postgresql
  encoding: unicode
  database: worksense
  pool: 5
  timeout: 5000
